### ISSUE TITLE
一个自动安装docker与运行docker镜像的脚本

### ISSUE THREAD

**Issue by chenaidairong** [Luoofan/autochaoxing#8]
一个自动安装docker与运行docker镜像的脚本
[我的网盘链接](https://pan.yjsn.club/s/1/%E6%9D%82%E8%B4%A7/%E7%BD%91%E8%AF%BE%E7%9B%B8%E5%85%B3%E7%A8%8B%E5%BA%8F%E5%92%8C%E4%BB%A3%E7%A0%81/chaoxing.sh.tar.gz)

**Comment by Luoofan** [comment]
@KimJungWha 测试后重写了sh脚本
支持debian，ubuntu，centos，redhat
在ubuntu和centos测试成功
**使用方法**：
1. `sudo chmod +x autocx.sh`
2. `sudo ./autocx.sh`

[autocx.zip](https://github.com/Luoofan/autochaoxing/files/4679694/autocx.zip)

**该issue将保持open**
**欢迎测试与反馈**
**感谢 @chenaidairong @KimJungWha**👍👍👍

**Comment by southcat** [comment]
Traceback (most recent call last):
  File "./src/login_courses.py", line 444, in <module>
    process.work()
  File "./src/login_courses.py", line 228, in work
    courses_lt = self._login()
  File "./src/login_courses.py", line 185, in _login
    p=Popen(['./src/viu', 'login_vercode.png'])
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './src/viu'


docker报错 centos环境

**Comment by southcat** [comment]
docker在国内服务器的配置速度太慢了 是镜像服务器的问题吗  用的一键脚本

**Comment by southcat** [comment]
Traceback (most recent call last):
  File "./src/login_courses.py", line 444, in <module>
    process.work()
  File "./src/login_courses.py", line 228, in work
    courses_lt = self._login()
  File "./src/login_courses.py", line 185, in _login
    p=Popen(['./src/viu', 'login_vercode.png'])
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './src/viu'

docker容器内报错

**Comment by Luoofan** [comment]
自动配置脚本的具体情况我不太清楚，需要 @KimJungWha 
根据你所提供的信息，目前你应该是已经配好了docker，但是在容器内执行脚本的时候出现了权限问题，你可以试试这两个办法：
- 查看并更改`./src/viu`的权限
- 执行脚本时加上`sudo`

**Comment by KimJungWha** [comment]
> docker在国内服务器的配置速度太慢了 是镜像服务器的问题吗 用的一键脚本
使用脚本安装软件慢，请更换国内的软件源，docker 部署 镜像时慢，可以更换 阿里云的镜像加速器

**Comment by KimJungWha** [comment]
> Traceback (most recent call last):
> File "./src/login_courses.py", line 444, in
> process.work()
> File "./src/login_courses.py", line 228, in work
> courses_lt = self._login()
> File "./src/login_courses.py", line 185, in _login
> p=Popen(['./src/viu', 'login_vercode.png'])
> File "/usr/lib/python3.6/subprocess.py", line 729, in **init**
> restore_signals, start_new_session)
> File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> PermissionError: [Errno 13] Permission denied: './src/viu'
> 
> docker容器内报错



我复现了这个报错，在使用学号登录时，调用 viu 填写验证码时的报错，第一次运行 viu 时提示无权限，授权后提示找不到文件，很遗憾我还没有解决问题。
- 您可以使用例如 `cacaview` 这样的同类软件，`vim src/login_courses.py`，将里面的 `./src/viu` 替换成您使用的软件
- 也可以使用手机号登录(推荐)

**Comment by 19819068211** [comment]
Welcome to Huawei Cloud Service

Last login: Tue Apr 20 08:54:33 2021 from 223.104.192.190
[root@hecs-x-medium-2-win-20210416095943 ~]# docker exec -it autocx sh
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
~ # vim logindata_phone.txt













































~ # python3 autocx.py
Set mode: single        rate: 1.00      noans_num:5
Welcome To Multi-Autocx!
 check your phonenum: 19819068211
 check your password: 19772001wqwq
 Traceback (most recent call last):
  File "./src/login_courses.py", line 447, in <module>
    process.work()
  File "./src/login_courses.py", line 236, in work
    with StartDriver() as chrome_driver:
  File "/root/src/startdriver.py", line 13, in __enter__
    self.driver=StartDriver.startchrome()
  File "/root/src/startdriver.py", line 79, in startchrome
    return webdriver.Chrome(options=chrome_options)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/lib/chromium/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.38 (f91d32489882be7df38da3422a19713bfd113fa5),platform=Linux 4.18.0-240.10.1.el8_3.x86_64 x86_64)
![Screenshot_20210420_090025_com sonelli juicessh](https://user-images.githubusercontent.com/66981884/115321727-03d04500-a1b7-11eb-838d-c288c082fe40.jpg)
请问出现如上报错应该如何处理
